name: Harmonia
version: '${project.version}'
main: net.harmoniamc.harmonia.Main
authors: [Harmonia]
description: Plugin including everything such as ranks, moderation commands, commands ect..
website: harmoniamc.net
